mod breath_transcribe;
mod continue_generation;
mod cpal_diag;
mod demos;
mod diphone_cache;
mod dogfood_two;
mod ear_scope;
mod go;
mod go1;
mod harmony_go;
mod live_half_duplex;
mod llama;
mod loop_trace;
mod mbrola_inventory;
mod mbrola_render;
mod mel_roundtrip;
mod mic_transcribe;
mod models;
mod prosody_plan;
mod round_trip;
mod sing_demo;
mod soundscape_debug;
#[cfg(any(test, feature = "asr-whisper"))]
mod source_inspection;
mod synthetic_cache;
mod think_say;
mod trace_viewer_export;
mod transcribe;
mod vad_calibration;
mod vad_trace;
mod web;

pub(crate) use breath_transcribe::run_breath_transcribe;
pub(crate) use continue_generation::run_continue;
pub(crate) use cpal_diag::{play_audio_frame_stream, play_audio_frames, prepare_audio_playback};
pub(crate) use cpal_diag::{run_play_wav, run_record_wav};
pub(crate) use demos::{run_demo_vad, run_fake_turn};
pub(crate) use diphone_cache::run_diphone;
pub(crate) use diphone_cache::run_diphone_cache;
pub(crate) use dogfood_two::run_dogfood_two;
pub(crate) use ear_scope::run_ear_scope;
pub(crate) use go::run_go;
pub(crate) use go1::run_go1;
pub(crate) use harmony_go::run_harmony_go;
pub(crate) use live_half_duplex::run_live_half_duplex;
pub(crate) use llama::run_llama_turn;
pub(crate) use loop_trace::run_loop_trace;
pub(crate) use mbrola_inventory::{run_mbrola_audit, run_mbrola_inventory};
pub(crate) use mbrola_render::run_mbrola_render;
pub(crate) use mel_roundtrip::run_mel_roundtrip;
pub(crate) use mic_transcribe::run_mic_transcribe;
pub(crate) use models::run_models;
pub(crate) use prosody_plan::run_prosody_plan;
pub(crate) use round_trip::run_round_trip_wav;
pub(crate) use sing_demo::run_sing_demo;
pub(crate) use soundscape_debug::run_soundscape_debug;
pub(crate) use synthetic_cache::run_synthetic_cache;
pub(crate) use think_say::run_think_say;
pub(crate) use trace_viewer_export::run_trace_viewer_export;
pub(crate) use transcribe::run_transcribe;
pub(crate) use vad_calibration::run_vad;
pub(crate) use vad_trace::run_vad_trace;
pub(crate) use web::run_web;

pub(crate) use crate::cli::piper::run_echo;
pub(crate) use crate::cli::piper::run_riper_compare;
pub(crate) use crate::cli::piper::run_say;
