pub struct ModelAsset {
    pub id: &'static str,
    pub filename: &'static str,
    pub relative_path: &'static str,
    pub url: &'static str,
    /// Expected file size in bytes. When set, the fetcher will fail if the
    /// downloaded file does not match. Leave `None` if the authoritative size
    /// is not known at compile time.
    pub expected_size_bytes: Option<u64>,
    /// Hex-encoded SHA-256 checksum of the file as distributed by the upstream
    /// source. When set, every download is verified against this digest before
    /// the file is promoted to its final path. Leave `None` only when the
    /// checksum is genuinely unknown; the integrity status will then be reported
    /// as `unknown-checksum` rather than silently passing.
    pub sha256: Option<&'static str>,
    /// SPDX license identifier or short description (e.g. `"MIT"`, `"Apache-2.0"`,
    /// `"CC-BY-4.0"`, `"proprietary"`).
    pub license: Option<&'static str>,
    /// Human-readable upstream source description (e.g. a repository URL or
    /// project name).
    pub source: Option<&'static str>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModelKind {
    Llm,
    Voice,
    Vocoder,
    Whisper,
}

pub struct ModelBundle {
    pub id: &'static str,
    pub display_name: &'static str,
    pub kind: ModelKind,
    pub asset_ids: &'static [&'static str],
    pub primary_asset_id: &'static str,
    pub aliases: &'static [&'static str],
}

pub const DEFAULT_MODELS: &[ModelAsset] = &[
    ModelAsset {
        id: "whisper-tiny-en",
        filename: "ggml-tiny.en.bin",
        relative_path: "models/whisper/ggml-tiny.en.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-tiny",
        filename: "ggml-tiny.bin",
        relative_path: "models/whisper/ggml-tiny.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-base-en",
        filename: "ggml-base.en.bin",
        relative_path: "models/whisper/ggml-base.en.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-base",
        filename: "ggml-base.bin",
        relative_path: "models/whisper/ggml-base.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-small-en",
        filename: "ggml-small.en.bin",
        relative_path: "models/whisper/ggml-small.en.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-small",
        filename: "ggml-small.bin",
        relative_path: "models/whisper/ggml-small.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-medium-en",
        filename: "ggml-medium.en.bin",
        relative_path: "models/whisper/ggml-medium.en.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.en.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-medium",
        filename: "ggml-medium.bin",
        relative_path: "models/whisper/ggml-medium.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-large-v1",
        filename: "ggml-large-v1.bin",
        relative_path: "models/whisper/ggml-large-v1.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v1.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-large-v2",
        filename: "ggml-large-v2.bin",
        relative_path: "models/whisper/ggml-large-v2.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v2.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-large-v3",
        filename: "ggml-large-v3.bin",
        relative_path: "models/whisper/ggml-large-v3.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "whisper-large-v3-turbo",
        filename: "ggml-large-v3-turbo.bin",
        relative_path: "models/whisper/ggml-large-v3-turbo.bin",
        url: "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggerganov/whisper.cpp"),
    },
    ModelAsset {
        id: "llama-3-2-3b-instruct-q4-k-m",
        filename: "llama-3.2-3b-instruct-q4_k_m.gguf",
        relative_path: "models/llama/llama-3.2-3b-instruct-q4_k_m.gguf",
        url: "https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q4_K_M-GGUF/resolve/main/llama-3.2-3b-instruct-q4_k_m.gguf",
        expected_size_bytes: None,
        sha256: None,
        license: Some("LicenseRef-Llama-3.2"),
        source: Some("https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q4_K_M-GGUF"),
    },
    ModelAsset {
        id: "gpt-oss-20b-mxfp4",
        filename: "gpt-oss-20b-mxfp4.gguf",
        relative_path: "models/llama/gpt-oss-20b-mxfp4.gguf",
        url: "https://huggingface.co/ggml-org/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-mxfp4.gguf",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/ggml-org/gpt-oss-20b-GGUF"),
    },
    ModelAsset {
        id: "gemma-3-4b-it-q4-k-m",
        filename: "gemma-3-4b-it-Q4_K_M.gguf",
        relative_path: "models/gemma/gemma-3-4b-it-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q4_K_M.gguf",
        expected_size_bytes: None,
        sha256: None,
        license: Some("LicenseRef-Gemma"),
        source: Some("https://huggingface.co/unsloth/gemma-3-4b-it-GGUF"),
    },
    ModelAsset {
        id: "gemma-4-e4b-it-q4-k-m",
        filename: "gemma-4-E4B-it-Q4_K_M.gguf",
        relative_path: "models/gemma/gemma-4-E4B-it-Q4_K_M.gguf",
        url: "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q4_K_M.gguf",
        expected_size_bytes: None,
        sha256: None,
        license: Some("LicenseRef-Gemma"),
        source: Some("https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF"),
    },
    ModelAsset {
        id: "piper-ryan-medium",
        filename: "en_US-ryan-medium.onnx",
        relative_path: "models/piper/en_US-ryan-medium.onnx",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-ryan-medium-config",
        filename: "en_US-ryan-medium.onnx.json",
        relative_path: "models/piper/en_US-ryan-medium.onnx.json",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx.json",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-amy-medium",
        filename: "en_US-amy-medium.onnx",
        relative_path: "models/piper/en_US-amy-medium.onnx",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-amy-medium-config",
        filename: "en_US-amy-medium.onnx.json",
        relative_path: "models/piper/en_US-amy-medium.onnx.json",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx.json",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-hfc-male-medium",
        filename: "en_US-hfc_male-medium.onnx",
        relative_path: "models/piper/en_US-hfc_male-medium.onnx",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-hfc-male-medium-config",
        filename: "en_US-hfc_male-medium.onnx.json",
        relative_path: "models/piper/en_US-hfc_male-medium.onnx.json",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx.json",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-hfc-female-medium",
        filename: "en_US-hfc_female-medium.onnx",
        relative_path: "models/piper/en_US-hfc_female-medium.onnx",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-hfc-female-medium-config",
        filename: "en_US-hfc_female-medium.onnx.json",
        relative_path: "models/piper/en_US-hfc_female-medium.onnx.json",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx.json",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-john-medium",
        filename: "en_US-john-medium.onnx",
        relative_path: "models/piper/en_US-john-medium.onnx",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/john/medium/en_US-john-medium.onnx",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-john-medium-config",
        filename: "en_US-john-medium.onnx.json",
        relative_path: "models/piper/en_US-john-medium.onnx.json",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/john/medium/en_US-john-medium.onnx.json",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-ljspeech-high",
        filename: "en_US-ljspeech-high.onnx",
        relative_path: "models/piper/en_US-ljspeech-high.onnx",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ljspeech/high/en_US-ljspeech-high.onnx",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC0-1.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-ljspeech-high-config",
        filename: "en_US-ljspeech-high.onnx.json",
        relative_path: "models/piper/en_US-ljspeech-high.onnx.json",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ljspeech/high/en_US-ljspeech-high.onnx.json",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC0-1.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-libritts-high",
        filename: "en_US-libritts-high.onnx",
        relative_path: "models/piper/en_US-libritts-high.onnx",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/en_US-libritts-high.onnx",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "piper-libritts-high-config",
        filename: "en_US-libritts-high.onnx.json",
        relative_path: "models/piper/en_US-libritts-high.onnx.json",
        url: "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/en_US-libritts-high.onnx.json",
        expected_size_bytes: None,
        sha256: None,
        license: Some("CC-BY-4.0"),
        source: Some("https://huggingface.co/rhasspy/piper-voices"),
    },
    ModelAsset {
        id: "hifigan-speecht5",
        filename: "speecht5_hifigan.onnx",
        relative_path: "models/vocoder/speecht5_hifigan.onnx",
        url: "https://huggingface.co/Xenova/speecht5_hifigan/resolve/main/onnx/model.onnx",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/Xenova/speecht5_hifigan"),
    },
    ModelAsset {
        id: "hifigan-speecht5-config",
        filename: "speecht5_hifigan.config.json",
        relative_path: "models/vocoder/speecht5_hifigan.config.json",
        url: "https://huggingface.co/Xenova/speecht5_hifigan/resolve/main/config.json",
        expected_size_bytes: None,
        sha256: None,
        license: Some("MIT"),
        source: Some("https://huggingface.co/Xenova/speecht5_hifigan"),
    },
];

pub const MODEL_BUNDLES: &[ModelBundle] = &[
    ModelBundle {
        id: "whisper-tiny-en",
        display_name: "Whisper tiny.en",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-tiny-en"],
        primary_asset_id: "whisper-tiny-en",
        aliases: &["tiny", "tiny.en", "whisper"],
    },
    ModelBundle {
        id: "whisper-tiny",
        display_name: "Whisper tiny",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-tiny"],
        primary_asset_id: "whisper-tiny",
        aliases: &["tiny-multilingual", "tiny.multi"],
    },
    ModelBundle {
        id: "whisper-base-en",
        display_name: "Whisper base.en",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-base-en"],
        primary_asset_id: "whisper-base-en",
        aliases: &["base.en", "base-english"],
    },
    ModelBundle {
        id: "whisper-base",
        display_name: "Whisper base",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-base"],
        primary_asset_id: "whisper-base",
        aliases: &["base", "base-multilingual", "base.multi"],
    },
    ModelBundle {
        id: "whisper-small-en",
        display_name: "Whisper small.en",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-small-en"],
        primary_asset_id: "whisper-small-en",
        aliases: &["small.en", "small-english"],
    },
    ModelBundle {
        id: "whisper-small",
        display_name: "Whisper small",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-small"],
        primary_asset_id: "whisper-small",
        aliases: &["small", "small-multilingual", "small.multi"],
    },
    ModelBundle {
        id: "whisper-medium-en",
        display_name: "Whisper medium.en",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-medium-en"],
        primary_asset_id: "whisper-medium-en",
        aliases: &["medium.en", "medium-english"],
    },
    ModelBundle {
        id: "whisper-medium",
        display_name: "Whisper medium",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-medium"],
        primary_asset_id: "whisper-medium",
        aliases: &["medium", "medium-multilingual", "medium.multi"],
    },
    ModelBundle {
        id: "whisper-large-v1",
        display_name: "Whisper large v1",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-large-v1"],
        primary_asset_id: "whisper-large-v1",
        aliases: &["large-v1"],
    },
    ModelBundle {
        id: "whisper-large-v2",
        display_name: "Whisper large v2",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-large-v2"],
        primary_asset_id: "whisper-large-v2",
        aliases: &["large-v2"],
    },
    ModelBundle {
        id: "whisper-large-v3",
        display_name: "Whisper large v3",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-large-v3"],
        primary_asset_id: "whisper-large-v3",
        aliases: &["large", "large-v3"],
    },
    ModelBundle {
        id: "whisper-large-v3-turbo",
        display_name: "Whisper large v3 turbo multilingual",
        kind: ModelKind::Whisper,
        asset_ids: &["whisper-large-v3-turbo"],
        primary_asset_id: "whisper-large-v3-turbo",
        aliases: &[
            "large-v3-turbo",
            "large-turbo",
            "turbo",
            "v3-turbo",
            "multilingual-v3-turbo",
        ],
    },
    ModelBundle {
        id: "llama-3-2-3b-instruct-q4-k-m",
        display_name: "Llama 3.2 3B Instruct Q4_K_M",
        kind: ModelKind::Llm,
        asset_ids: &["llama-3-2-3b-instruct-q4-k-m"],
        primary_asset_id: "llama-3-2-3b-instruct-q4-k-m",
        aliases: &["llama", "llama-3.2", "llama3.2", "current"],
    },
    ModelBundle {
        id: "gpt-oss-20b-mxfp4",
        display_name: "gpt-oss 20B MXFP4",
        kind: ModelKind::Llm,
        asset_ids: &["gpt-oss-20b-mxfp4"],
        primary_asset_id: "gpt-oss-20b-mxfp4",
        aliases: &["gpt-oss", "gpt-oss-20b", "oss"],
    },
    ModelBundle {
        id: "gemma-3-4b-it-q4-k-m",
        display_name: "Gemma 3 4B IT Q4_K_M",
        kind: ModelKind::Llm,
        asset_ids: &["gemma-3-4b-it-q4-k-m"],
        primary_asset_id: "gemma-3-4b-it-q4-k-m",
        aliases: &[
            "gemma3",
            "gemma-3",
            "gemma-3-4b",
            "gemma-3-4b-it-q4-0",
            "gemma",
        ],
    },
    ModelBundle {
        id: "gemma-4-e4b-it-q4-k-m",
        display_name: "Gemma 4 E4B IT Q4_K_M",
        kind: ModelKind::Llm,
        asset_ids: &["gemma-4-e4b-it-q4-k-m"],
        primary_asset_id: "gemma-4-e4b-it-q4-k-m",
        aliases: &["gemma4", "gemma-4", "gemma-4-e4b"],
    },
    ModelBundle {
        id: "ryan",
        display_name: "Ryan",
        kind: ModelKind::Voice,
        asset_ids: &["piper-ryan-medium", "piper-ryan-medium-config"],
        primary_asset_id: "piper-ryan-medium",
        aliases: &["piper-ryan-medium"],
    },
    ModelBundle {
        id: "amy",
        display_name: "Amy",
        kind: ModelKind::Voice,
        asset_ids: &["piper-amy-medium", "piper-amy-medium-config"],
        primary_asset_id: "piper-amy-medium",
        aliases: &["piper-amy-medium"],
    },
    ModelBundle {
        id: "hfc-male",
        display_name: "HFC Male",
        kind: ModelKind::Voice,
        asset_ids: &["piper-hfc-male-medium", "piper-hfc-male-medium-config"],
        primary_asset_id: "piper-hfc-male-medium",
        aliases: &["hfc_male", "male", "piper-hfc-male-medium"],
    },
    ModelBundle {
        id: "hfc-female",
        display_name: "HFC Female",
        kind: ModelKind::Voice,
        asset_ids: &["piper-hfc-female-medium", "piper-hfc-female-medium-config"],
        primary_asset_id: "piper-hfc-female-medium",
        aliases: &["hfc_female", "female", "piper-hfc-female-medium"],
    },
    ModelBundle {
        id: "john",
        display_name: "John",
        kind: ModelKind::Voice,
        asset_ids: &["piper-john-medium", "piper-john-medium-config"],
        primary_asset_id: "piper-john-medium",
        aliases: &["piper-john-medium"],
    },
    ModelBundle {
        id: "ljspeech",
        display_name: "LJSpeech",
        kind: ModelKind::Voice,
        asset_ids: &["piper-ljspeech-high", "piper-ljspeech-high-config"],
        primary_asset_id: "piper-ljspeech-high",
        aliases: &["lj", "piper-ljspeech-high"],
    },
    ModelBundle {
        id: "libritts",
        display_name: "LibriTTS",
        kind: ModelKind::Voice,
        asset_ids: &["piper-libritts-high", "piper-libritts-high-config"],
        primary_asset_id: "piper-libritts-high",
        aliases: &["piper-libritts-high"],
    },
    ModelBundle {
        id: "speecht5-hifigan",
        display_name: "SpeechT5 HiFi-GAN",
        kind: ModelKind::Vocoder,
        asset_ids: &["hifigan-speecht5", "hifigan-speecht5-config"],
        primary_asset_id: "hifigan-speecht5",
        aliases: &["hifigan", "hifigan-speecht5", "speecht5_hifigan"],
    },
];
